Catalan translations (ca-ES)
StateOfJS/state-of-js-graphql-results-api pull request #123
Opened 2020-12-30 12:56 UTC by socunanena

2020-12-30 14:24 UTC, sviridoff requested changes

2020-12-30 14:24 UTC, sviridoff commented on src/i18n/ru-RU/results.yml
> +      t: Каталонский
Каталанский is more commonly used when is referred to the language

2020-12-30 22:21 UTC, SachaG commented
Great! Let me know when this is ready to merge :)

2020-12-31 14:39 UTC, socunanena commented
> Great! Let me know when this is ready to merge :)

I just fixed a change requested by @sviridoff . For me, it's ready to go to prod if you think all files are ok.

Thanks for your quick response!

2020-12-31 22:31 UTC, merged

2020-12-31 22:31 UTC, SachaG commented
:+1:

2021-01-01 07:51 UTC, socunanena commented
Thanks!

I'm not able to see it in production, is there anything missing in my code? Or there is just needed some manual action to be deployed?

2021-01-01 07:56 UTC, SachaG commented
Oh yeah sorry I will need to redeploy a couple things before it's live. I'll try to do it early next week :)